{
 "title": "DocGraf",
 "description": "A starter Grafana dashboard for monitoring Docker Events",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "MetricSource", "query": "prometheus" },
   { "name": "LogsSource", "query": "loki" },
   {
    "name": "ContainerName",
    "query": {
     "query": "label_values(docgraf_docker_events_recv, container)"
    }
   },
   {
    "name": "EventType",
    "query": {
     "query": "label_values(docgraf_docker_events_recv, event_type)"
    }
   },
   {
    "name": "Event",
    "query": {
     "query": "label_values(docgraf_docker_events_recv, event)"
    }
   },
   {
    "name": "Image",
    "query": {
     "query": "label_values(docgraf_docker_events_recv, image)"
    }
   }
  ]
 },
 "panels": [
  { "title": "README", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "# DocGraf Example Dashboard\n\n## Filters\n\nFilters can be applied to view different subsets of the data.\n\n* MetricSource - Your metrics Datasource\n* LogSrouce - Your logs Datasource\n* ContainerName - Filter for events for a given container\n* EventType - Filter by a specific EventType\n* Event - Filter by a specific Event\n* Image - Filter for events for a given image\n\n## Container Events Annotations\n\nA toggle is provided for displaying docker container events as annotations."
   }
  },
  {
   "title": "Events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "All Events",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "sum(irate(docgraf_docker_events_recv{event_type=~\"$EventType\", event=~\"$Event\", image=~\"$Image\", container=~\"$ContainerName\"}[$__rate_interval]))",
       "legendFormat": "Events Recv"
      },
      {
       "expr": "sum(irate(docgraf_docker_events_recorded{event_type=~\"$EventType\", event=~\"$Event\", image=~\"$Image\", container=~\"$ContainerName\"}[$__rate_interval]))",
       "legendFormat": "Events Recorded"
      }
     ]
    },
    {
     "title": "All Events by Container",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
     "targets": [
      {
       "expr": "sum by(container) (irate(docgraf_docker_events_recv{event_type=~\"$EventType\", event=~\"$Event\", image=~\"$Image\", container=~\"$ContainerName\"}[$__rate_interval]))",
       "legendFormat": "{{ container }}"
      }
     ]
    },
    {
     "title": "All Events by Event Type",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "sum(irate(docgraf_docker_events_recv{event_type=~\"$EventType\", event=~\"$Event\", image=~\"$Image\", container=~\"$ContainerName\"}[$__rate_interval])) by (event_type)",
       "legendFormat": "{{ event_type}}"
      }
     ]
    },
    {
     "title": "All Events by Event",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 23 },
     "targets": [
      {
       "expr": "sum(irate(docgraf_docker_events_recv{event_type=~\"$EventType\", event=~\"$Event\", image=~\"$Image\", container=~\"$ContainerName\"}[$__rate_interval])) by (event)",
       "legendFormat": "{{ event}}"
      }
     ]
    },
    {
     "type": "piechart",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(sum_over_time(docgraf_docker_events_recorded{event_type=~\"$EventType\", event=~\"$Event\", image=~\"$Image\", container=~\"$ContainerName\"}[$__interval]))",
       "legendFormat": "Events Recorded"
      },
      {
       "expr": "sum(sum_over_time(docgraf_docker_events_recv{event_type=~\"$EventType\", event=~\"$Event\", image=~\"$Image\", container=~\"$ContainerName\"}[$__interval])) \r\n- \r\nsum(sum_over_time(docgraf_docker_events_recorded{event_type=~\"$EventType\", event=~\"$Event\", image=~\"$Image\", container=~\"$ContainerName\"}[$__interval]))",
       "legendFormat": "Events Received"
      }
     ]
    }
   ]
  },
  {
   "title": "Event Annotations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    { "title": "Events", "type": "annolist", "gridPos": { "h": 12, "w": 24, "x": 0, "y": 15 } }
   ]
  },
  {
   "title": "DocGraf Service Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    { "type": "text", "gridPos": { "h": 4, "w": 18, "x": 0, "y": 16 }, "options": { "content": "# DocGraf Service Monitoring\n" } },
    {
     "title": "Version",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 18, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "docgraf_build_info{}" }
     ]
    },
    {
     "title": "DotNet Runtime",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 21, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "docgraf_build_info{}" }
     ]
    },
    {
     "title": "OS Version",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 18, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "docgraf_build_info{}" }
     ]
    },
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 21, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "dtdurations" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "time() - process_start_time_seconds{job=\"docgraf\"}"
      }
     ]
    },
    {
     "title": "Logs",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 10, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by(level) (rate({container_name=\"docgraf\"} | json | __error__ != `JSONParserErr` [1m]))",
       "legendFormat": "{{level}}"
      }
     ]
    },
    {
     "title": "CPU",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 14, "x": 10, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{job=\"docgraf\"}[$__interval])",
       "legendFormat": "{{instance}} CPU Process Seconds"
      }
     ]
    },
    {
     "title": "Logs",
     "type": "logs",
     "gridPos": { "h": 16, "w": 10, "x": 0, "y": 24 },
     "targets": [
      {
       "bucketAggs": [
        { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "{container_name=\"docgraf\"}",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 14, "x": 10, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "dotnet_total_memory_bytes{job=\"docgraf\"}",
       "legendFormat": "DotNet Total Memory Bytes"
      },
      {
       "expr": "process_working_set_bytes{job=\"docgraf\"}",
       "legendFormat": "Process Working Set (RAM)"
      },
      {
       "expr": "process_private_memory_bytes{job=\"docgraf\"}",
       "legendFormat": "Process Private Memory Bytes"
      },
      {
       "expr": "process_virtual_memory_bytes{job=\"docgraf\"}",
       "legendFormat": "Process Virtual Memory Bytes"
      }
     ]
    },
    {
     "title": "Num Threads",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 14, "x": 10, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "increase(process_num_threads{job=\"docgraf\"}[$__interval])"
      }
     ]
    }
   ]
  },
  {
   "title": "Scrape Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "up{job=\"docgraf\"}"
      }
     ]
    },
    {
     "title": "Samples Scraped",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 3, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "scrape_samples_scraped{job=\"docgraf\"}"
      }
     ]
    },
    {
     "title": "Scrape Duration Seconds",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 17, "x": 7, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "irate(scrape_duration_seconds{job=\"docgraf\"}[$__rate_interval])"
      }
     ]
    }
   ]
  }
 ]
}